name: Rust

on:
  push:
    tags:
      - v**

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - name: Install system dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install -y \
          libdbus-1-dev musl-tools
      - name: Build
        run: cargo build --all --release --target x86_64-unknown-linux-musl && strip target/x86_64-unknown-linux-musl/release/zsh-histdb-skim target/x86_64-unknown-linux-musl/release/zsh-histdb-skim
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zsh-histdb-skim-linux-x64
          path: target/x86_64-unknown-linux-musl/release/zsh-histdb-skim
          if-no-files-found: error


